/**
 * Alimenti base in italiano → voce USDA FoodData Central (SR Legacy, pubblico dominio).
 * [nome italiano, descrizione USDA (inizio del nome) oppure valori medi {kcal,p,c,f} se assente in USDA, categoria, grammi di 1 pezzo/porzione tipica, parole chiave extra]
 * Usato da scripts/build-foods.mjs per generare public/foods.json (valori per 100 g).
 */
export const FOODS_IT = [
  // Cereali, pane, pasta
  ['Pasta di semola (cruda)', 'Pasta, dry, unenriched', 'cereali', 80, 'spaghetti spaghettini penne fusilli rigatoni maccheroni bucatini linguine paccheri orecchiette farfalle mezze maniche pasta pennette risoni ditalini fedelini vermicelli trofie malloreddus fileja ferricelli bigoli pici strozzapreti tubetti conchiglie calamarata cavatelli trenette ziti candele caserecce gemelli'],
  ['Pasta integrale (cruda)', 'Pasta, whole-wheat, dry', 'cereali', 80, "pasta_integrale"],
  ['Pasta all\'uovo (cruda)', 'Noodles, egg, dry, unenriched', 'cereali', 80, "tagliatelle fettuccine pappardelle lasagne tagliolini tajarin all'uovo sfoglie_per_lasagne"],
  ['Pasta cotta', 'Pasta, cooked, unenriched, without added salt', 'cereali', 200, ''],
  ['Gnocchi di patate', 'Gnocchi, potato', 'cereali', 200, 'gnocchi'],
  ['Riso bianco (crudo)', 'Rice, white, long-grain, regular, raw, unenriched', 'cereali', 80, 'riso carnaroli arborio vialone basmati'],
  ['Riso integrale (crudo)', 'Rice, brown, long-grain, raw', 'cereali', 80, ''],
  ['Riso bianco cotto', 'Rice, white, long-grain, regular, unenriched, cooked without salt', 'cereali', 180, ''],
  ['Pane comune', 'Bread, italian', 'cereali', 50, 'pane pane_casereccio ciabatta filone baguette pagnotta rosetta'],
  ['Pane integrale', 'Bread, whole-wheat, commercially prepared', 'cereali', 50, "pane_integrale"],
  ['Pan carré', 'Bread, white, commercially prepared (includes soft bread crumbs)', 'cereali', 25, 'bauletto tramezzino pancarre pan_carre'],
  ['Pangrattato', 'Bread, crumbs, dry, grated, plain', 'cereali', 10, "pan_grattato pane_grattugiato"],
  ['Fette biscottate', 'Crackers, rusk toast', 'cereali', 10, "fetta_biscottata fette_biscottate"],
  ['Crackers', 'Crackers, standard snack-type, regular', 'cereali', 25, 'cracker'],
  ['Grissini', 'Breadsticks, hard, NFS', 'cereali', 10, 'grissino'],
  ['Farina di grano tenero 00', 'Wheat flour, white, all-purpose, unenriched', 'cereali', 0, "farina farina_00 manitoba frumento farina_bianca"],
  ['Farina integrale', 'Wheat flour, whole-grain', 'cereali', 0, "farina_integrale frumento_integrale"],
  ['Semola di grano duro', 'Semolina, unenriched', 'cereali', 0, 'semolino semola'],
  ['Farina di mais (polenta)', 'Cornmeal, degermed, unenriched, yellow', 'cereali', 70, "polenta fioretto bramata farina_gialla farina_di_mais"],
  ['Fiocchi d\'avena', 'Cereals, oats, regular and quick, not fortified, dry', 'cereali', 40, 'avena porridge'],
  ['Corn flakes', 'Cereal, corn flakes, plain', 'cereali', 30, 'cereali colazione'],
  ['Muesli', { kcal: 367, p: 9.7, c: 66, f: 6.2 }, 'cereali', 40, ''],
  ['Orzo perlato', 'Barley, pearled, raw', 'cereali', 70, 'orzo'],
  ['Farro', 'Spelt, uncooked', 'cereali', 70, 'farro'],
  ['Cous cous (crudo)', 'Couscous, dry', 'cereali', 70, 'cuscus'],
  ['Quinoa (cruda)', 'Quinoa, uncooked', 'cereali', 70, ''],
  ['Piadina / tortilla', 'Tortillas, ready-to-bake or -fry, flour', 'cereali', 60, 'piadina tortilla wrap'],
  ['Pizza margherita', 'Pizza, cheese topping, regular crust, frozen, cooked', 'cereali', 300, 'pizza'],
  ['Pasta sfoglia', 'Puff pastry, frozen, ready-to-bake', 'cereali', 0, 'sfoglia'],
  ['Pasta brisée', 'Pie crust, standard-type, frozen, ready-to-bake, unenriched', 'cereali', 0, 'brisè brisee'],
  ['Gallette di riso', 'Snacks, rice cakes, brown rice, plain', 'cereali', 9, 'galletta gallette'],

  // Carne
  ['Petto di pollo', 'Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw', 'carne', 150, "pollo petto_di_pollo"],
  ['Cosce di pollo', 'Chicken, broilers or fryers, dark meat, thigh, meat only, raw', 'carne', 150, 'coscia sovracosce'],
  ['Pollo intero', 'Chicken, broilers or fryers, meat and skin, raw', 'carne', 0, 'pollo'],
  ['Petto di tacchino', 'Turkey, whole, breast, meat only, raw', 'carne', 150, "tacchino"],
  ['Manzo magro (fettine)', 'Beef, round, top round roast, boneless, separable lean only, trimmed to 0" fat, select, raw', 'carne', 150, 'manzo fettine bistecca girello scamone vitellone coda_di_bue spezzatino polpa_di_manzo'],
  ['Carne macinata di manzo', 'Beef, ground, 85% lean meat / 15% fat, raw', 'carne', 150, "macinato carne_macinata"],
  ['Macinato magro di manzo', 'Beef, ground, 95% lean meat / 5% fat, raw', 'carne', 150, 'magro'],
  ['Vitello', 'Veal, leg (top round), separable lean only, raw', 'carne', 150, "vitello scaloppine"],
  ['Maiale (lonza)', 'Pork, fresh, loin, center loin (chops), bone-in, separable lean only, raw', 'carne', 150, 'maiale lonza braciola arista'],
  ['Salsiccia', 'Sausage, Italian, pork, mild, raw', 'carne', 100, 'salsiccia salsicce luganega'],
  ['Agnello', 'Lamb, New Zealand, imported, leg chop/steak, bone-in, separable lean only, raw', 'carne', 150, 'agnello abbacchio'],
  ['Coniglio', 'Game meat, rabbit, domesticated, composite of cuts, raw', 'carne', 150, 'coniglio'],
  ['Prosciutto crudo', 'Ham, prosciutto', 'carne', 50, 'crudo parma san daniele speck'],
  ['Prosciutto cotto', 'Ham, sliced, pre-packaged, deli meat (96%fat free, water added)', 'carne', 50, "prosciutto_cotto"],
  ['Bresaola', 'Beef, cured, dried', 'carne', 50, 'bresaola'],
  ['Pancetta', 'Pork, cured, bacon, unprepared', 'carne', 30, 'pancetta guanciale lardo bacon'],
  ['Salame', 'Salami, dry or hard, pork', 'carne', 30, 'salame'],
  ['Mortadella', 'Bologna, pork', 'carne', 30, 'mortadella'],
  ['Wurstel', 'Frankfurter, beef, unheated', 'carne', 50, 'wurstel würstel'],
  ['Fegato di vitello', 'Beef, variety meats and by-products, liver, raw', 'carne', 150, 'fegato'],

  // Pesce
  ['Salmone', 'Fish, salmon, Atlantic, farmed, raw', 'pesce', 150, 'salmone'],
  ['Salmone affumicato', 'Fish, salmon, chinook, smoked', 'pesce', 50, 'affumicato'],
  ['Tonno fresco', 'Fish, tuna, fresh, yellowfin, raw', 'pesce', 150, 'tonno'],
  ['Tonno al naturale', 'Fish, tuna, light, canned in water, drained solids', 'pesce', 80, "tonno_al_naturale tonno_in_scatola"],
  ['Tonno sott\'olio (sgocciolato)', 'Fish, tuna, light, canned in oil, drained solids', 'pesce', 80, "sott'olio"],
  ['Merluzzo', 'Fish, cod, Atlantic, raw', 'pesce', 150, 'merluzzo nasello baccalà'],
  ['Baccalà (secco)', 'Fish, cod, Atlantic, dried and salted', 'pesce', 0, 'baccalà stoccafisso'],
  ['Orata / branzino', 'Fish, sea bass, mixed species, raw', 'pesce', 200, 'orata branzino spigola'],
  ['Pesce spada', 'Fish, swordfish, raw', 'pesce', 150, 'spada pescespada'],
  ['Sgombro', 'Fish, mackerel, Atlantic, raw', 'pesce', 150, 'sgombro'],
  ['Alici / acciughe', 'Fish, anchovy, european, raw', 'pesce', 100, 'alici acciughe'],
  ['Acciughe sott\'olio', 'Fish, anchovy, european, canned in oil, drained solids', 'pesce', 10, "filetti_di_acciuga acciughe_sott'olio"],
  ['Sardine', 'Fish, sardine, Atlantic, canned in oil, drained solids with bone', 'pesce', 100, 'sardine sarde'],
  ['Trota', 'Fish, trout, rainbow, farmed, raw', 'pesce', 150, 'trota'],
  ['Gamberi', 'Crustaceans, shrimp, raw', 'pesce', 150, 'gamberi gamberetti mazzancolle scampi'],
  ['Calamari', 'Mollusks, squid, mixed species, raw', 'pesce', 150, 'calamari seppie totani'],
  ['Polpo', 'Mollusks, octopus, common, raw', 'pesce', 200, 'polpo moscardini'],
  ['Cozze', 'Mollusks, mussel, blue, raw', 'pesce', 150, 'cozze'],
  ['Vongole', 'Mollusks, clam, mixed species, raw', 'pesce', 150, 'vongole telline'],

  // Uova e latticini
  ['Uovo intero', 'Egg, whole, raw, fresh', 'uova-latticini', 55, 'uova uovo'],
  ['Albume', 'Egg, white, raw, fresh', 'uova-latticini', 33, "albumi chiare chiare_d'uovo"],
  ['Tuorlo', 'Egg, yolk, raw, fresh', 'uova-latticini', 18, "tuorli rosso_d'uovo"],
  ['Latte intero', 'Milk, whole, 3.25% milkfat, with added vitamin D', 'uova-latticini', 200, "latte latte_intero"],
  ['Latte parzialmente scremato', 'Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D', 'uova-latticini', 200, 'latte ps'],
  ['Latte scremato', 'Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)', 'uova-latticini', 200, ''],
  ['Yogurt bianco intero', 'Yogurt, plain, whole milk', 'uova-latticini', 125, 'yogurt yoghurt'],
  ['Yogurt greco 0%', 'Yogurt, Greek, plain, nonfat', 'uova-latticini', 170, 'greco skyr'],
  ['Yogurt greco intero', 'Yogurt, Greek, plain, whole milk', 'uova-latticini', 170, ''],
  ['Parmigiano Reggiano', 'Cheese, parmesan, hard', 'uova-latticini', 10, "parmigiano grana_padano grana_grattugiato scaglie_di_grana formaggio_grattugiato formaggio_grana"],
  ['Pecorino', 'Cheese, romano', 'uova-latticini', 10, 'pecorino romano'],
  ['Mozzarella', 'Cheese, mozzarella, whole milk', 'uova-latticini', 125, 'mozzarella fiordilatte bufala'],
  ['Mozzarella light', 'Cheese, mozzarella, part skim milk', 'uova-latticini', 125, 'light'],
  ['Ricotta vaccina', 'Cheese, ricotta, whole milk', 'uova-latticini', 100, 'ricotta'],
  ['Ricotta light', 'Cheese, ricotta, part skim milk', 'uova-latticini', 100, ''],
  ['Fiocchi di latte', 'Cheese, cottage, lowfat, 2% milkfat', 'uova-latticini', 150, 'cottage'],
  ['Formaggio spalmabile', 'Cheese, cream', 'uova-latticini', 30, "philadelphia spalmabile formaggio_spalmabile"],
  ['Mascarpone', { kcal: 429, p: 4.6, c: 4.8, f: 44 }, 'uova-latticini', 30, "mascarpone"],
  ['Gorgonzola', 'Cheese, blue', 'uova-latticini', 30, 'gorgonzola'],
  ['Fontina / formaggio stagionato', 'Cheese, fontina', 'uova-latticini', 30, "formaggio fontina asiago emmental provolone scamorza provola caciocavallo taleggio castelmagno raschera toma montasio formaggi"],
  ['Feta', 'Cheese, feta', 'uova-latticini', 30, 'feta'],
  ['Burro', 'Butter, without salt', 'grassi', 10, 'burro margarina'],
  ['Panna fresca', 'Cream, fluid, heavy whipping', 'uova-latticini', 50, 'panna'],
  ['Panna da cucina', 'Cream, fluid, light (coffee cream or table cream)', 'uova-latticini', 50, 'cucina'],

  // Legumi
  ['Ceci secchi', 'Chickpeas (garbanzo beans, bengal gram), mature seeds, raw', 'legumi', 70, 'ceci'],
  ['Ceci in scatola', 'Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained, rinsed in tap water', 'legumi', 120, "ceci_lessati ceci_in_scatola"],
  ['Fagioli borlotti secchi', 'Beans, cranberry (roman), mature seeds, raw', 'legumi', 70, 'fagioli borlotti'],
  ['Fagioli cannellini secchi', 'Beans, white, mature seeds, raw', 'legumi', 70, 'cannellini'],
  ['Fagioli in scatola', 'Beans, kidney, red, mature seeds, canned, drained solids', 'legumi', 120, "fagioli_lessati borlotti_lessati cannellini_lessati fagioli_in_scatola"],
  ['Lenticchie secche', 'Lentils, raw', 'legumi', 70, 'lenticchie'],
  ['Lenticchie cotte', 'Lentils, mature seeds, cooked, boiled, without salt', 'legumi', 150, "lenticchie_lessate lenticchie_cotte"],
  ['Piselli', 'Peas, green, frozen, unprepared', 'legumi', 100, 'piselli pisellini'],
  ['Fave', 'Broadbeans (fava beans), mature seeds, raw', 'legumi', 70, 'fave'],
  ['Edamame', 'Edamame, frozen, unprepared', 'legumi', 100, ''],
  ['Tofu', 'Tofu, firm, prepared with calcium sulfate and magnesium chloride (nigari)', 'legumi', 100, 'tofu'],
  ['Tempeh', 'Tempeh', 'legumi', 100, ''],
  ['Latte di soia', 'Soymilk, original and vanilla, unfortified', 'legumi', 200, 'soia bevanda'],
  ['Hummus', 'Hummus, commercial', 'legumi', 50, 'hummus'],

  // Verdure
  ['Pomodori', 'Tomatoes, red, ripe, raw, year round average', 'verdura', 120, "pomodori pomodoro ramati pomodori_ciliegini datterini pachino pomodorini cuore_di_bue"],
  ['Passata di pomodoro', 'Tomato products, canned, puree, without salt added', 'verdura', 100, 'passata salsa_di_pomodoro conserva_di_pomodoro'],
  ['Pomodori pelati', 'Tomatoes, red, ripe, canned, packed in tomato juice', 'verdura', 400, 'pelati pomodori_pelati polpa_di_pomodoro'],
  ['Concentrato di pomodoro', 'Tomato products, canned, paste, without salt added', 'verdura', 15, 'concentrato doppio'],
  ['Pomodori secchi', 'Tomatoes, sun-dried', 'verdura', 10, 'secchi'],
  ['Zucchine', 'Squash, summer, zucchini, includes skin, raw', 'verdura', 200, 'zucchina zucchine'],
  ['Melanzane', 'Eggplant, raw', 'verdura', 300, 'melanzana melanzane'],
  ['Peperoni', 'Peppers, sweet, red, raw', 'verdura', 200, 'peperone peperoni'],
  ['Carote', 'Carrots, raw', 'verdura', 80, 'carota carote'],
  ['Cipolla', 'Onions, raw', 'verdura', 100, 'cipolla cipolle cipollotto cipollotti scalogno porro porri'],
  ['Aglio', 'Garlic, raw', 'verdura', 3, 'aglio spicchio'],
  ['Sedano', 'Celery, raw', 'verdura', 40, 'sedano costa'],
  ['Patate', 'Potatoes, flesh and skin, raw', 'verdura', 200, 'patata patate'],
  ['Patate dolci', 'Sweet potato, raw, unprepared', 'verdura', 200, 'batata patata_americana'],
  ['Spinaci', 'Spinach, raw', 'verdura', 200, 'spinaci'],
  ['Bietole', 'Chard, swiss, raw', 'verdura', 200, 'bietole bieta erbette'],
  ['Broccoli', 'Broccoli, raw', 'verdura', 200, 'broccoli broccolo cime di rapa friarielli'],
  ['Cavolfiore', 'Cauliflower, raw', 'verdura', 200, "cavolfiore"],
  ['Cavolo cappuccio / verza', 'Cabbage, raw', 'verdura', 200, "verza cappuccio cavolo cavolo_nero"],
  ['Insalata / lattuga', 'Lettuce, green leaf, raw', 'verdura', 80, 'lattuga insalata iceberg songino misticanza'],
  ['Rucola', 'Arugula, raw', 'verdura', 30, 'rucola'],
  ['Radicchio', 'Radicchio, raw', 'verdura', 100, 'radicchio indivia scarola'],
  ['Cetrioli', 'Cucumber, with peel, raw', 'verdura', 150, 'cetriolo cetrioli'],
  ['Finocchi', 'Fennel, bulb, raw', 'verdura', 200, 'finocchio finocchi'],
  ['Carciofi', 'Artichokes, (globe or french), raw', 'verdura', 120, 'carciofo carciofi'],
  ['Asparagi', 'Asparagus, raw', 'verdura', 150, 'asparagi'],
  ['Fagiolini', 'Beans, snap, green, raw', 'verdura', 150, 'fagiolini cornetti'],
  ['Funghi champignon', 'Mushrooms, white, raw', 'verdura', 150, 'funghi champignon porcini chiodini'],
  ['Funghi porcini secchi', 'Mushrooms, shiitake, dried', 'verdura', 10, 'secchi'],
  ['Zucca', 'Pumpkin, raw', 'verdura', 200, 'zucca'],
  ['Mais dolce', 'Corn, sweet, yellow, canned, whole kernel, drained solids', 'verdura', 80, 'mais'],
  ['Olive', 'Olives, ripe, canned (small-extra large)', 'verdura', 30, 'olive taggiasche'],
  ['Capperi', 'Capers, canned', 'verdura', 10, 'capperi'],
  ['Basilico', 'Basil, fresh', 'verdura', 3, 'basilico'],
  ['Prezzemolo', 'Parsley, fresh', 'verdura', 5, 'prezzemolo'],
  ['Verdure miste (contorno)', 'Vegetables, mixed, frozen, unprepared', 'verdura', 200, 'verdure contorno minestrone'],

  // Frutta
  ['Mela', 'Apples, raw, with skin', 'frutta', 180, 'mela mele'],
  ['Pera', 'Pears, raw', 'frutta', 170, 'pera pere'],
  ['Banana', 'Bananas, raw', 'frutta', 120, 'banana banane'],
  ['Arancia', 'Oranges, raw, all commercial varieties', 'frutta', 180, "arancia arance spremuta_d'arancia"],
  ['Mandarini', 'Tangerines, (mandarin oranges), raw', 'frutta', 80, 'mandarino clementine'],
  ['Limone (succo)', 'Lemon juice, raw', 'frutta', 15, 'limone limoni succo lime'],
  ['Kiwi', 'Kiwifruit, green, raw', 'frutta', 80, 'kiwi'],
  ['Fragole', 'Strawberries, raw', 'frutta', 150, 'fragole'],
  ['Frutti di bosco', 'Blueberries, raw', 'frutta', 100, 'mirtilli lamponi more frutti di bosco'],
  ['Uva', 'Grapes, red or green (European type, such as Thompson seedless), raw', 'frutta', 150, 'uva'],
  ['Pesche', 'Peaches, yellow, raw', 'frutta', 150, 'pesca pesche nettarine albicocche'],
  ['Ananas', 'Pineapple, raw, all varieties', 'frutta', 150, 'ananas'],
  ['Anguria', 'Watermelon, raw', 'frutta', 300, 'anguria cocomero'],
  ['Melone', 'Melons, cantaloupe, raw', 'frutta', 200, 'melone'],
  ['Ciliegie', 'Cherries, sweet, raw', 'frutta', 150, 'ciliegie'],
  ['Fichi', 'Figs, raw', 'frutta', 50, 'fichi'],
  ['Avocado', 'Avocados, raw, all commercial varieties', 'frutta', 150, 'avocado'],
  ['Datteri', 'Dates, medjool', 'frutta', 24, 'datteri'],
  ['Uvetta', 'Raisins, dark, seedless', 'frutta', 15, 'uvetta uva_passa uva_secca uva_passolina uva_sultanina sultanina'],
  ['Prugne secche', 'Plums, dried (prunes), uncooked', 'frutta', 30, 'prugne'],

  // Frutta secca e semi
  ['Mandorle', 'Nuts, almonds', 'frutta-secca', 30, 'mandorle'],
  ['Noci', 'Nuts, walnuts, english', 'frutta-secca', 30, 'noci gherigli'],
  ['Nocciole', 'Nuts, hazelnuts or filberts', 'frutta-secca', 30, 'nocciole'],
  ['Pistacchi', 'Nuts, pistachio nuts, raw', 'frutta-secca', 30, 'pistacchi'],
  ['Anacardi', 'Nuts, cashew nuts, raw', 'frutta-secca', 30, 'anacardi'],
  ['Arachidi', 'Peanuts, all types, raw', 'frutta-secca', 30, 'arachidi noccioline'],
  ['Burro d\'arachidi', 'Peanut butter, smooth style, without salt', 'frutta-secca', 15, 'burro di arachidi'],
  ['Pinoli', 'Nuts, pine nuts, dried', 'frutta-secca', 10, 'pinoli'],
  ['Semi di chia', 'Seeds, chia seeds, dried', 'frutta-secca', 10, 'chia'],
  ['Semi di lino', 'Seeds, flaxseed', 'frutta-secca', 10, 'lino'],
  ['Semi di sesamo', 'Seeds, sesame seeds, whole, dried', 'frutta-secca', 10, 'sesamo'],
  ['Semi di girasole / zucca', 'Seeds, sunflower seed kernels, dried', 'frutta-secca', 15, 'girasole semi di zucca'],
  ['Cocco rapè', 'Nuts, coconut meat, dried (desiccated), not sweetened', 'frutta-secca', 10, 'cocco'],

  // Grassi e condimenti
  ['Olio extravergine d\'oliva', 'Oil, olive, salad or cooking', 'grassi', 10, "olio olio_evo extravergine olio_di_oliva olio_d'oliva olio_extra olio_extravergine"],
  ['Olio di semi', 'Oil, sunflower, linoleic, (approx. 65%)', 'grassi', 10, "olio_di_semi olio_per_friggere olio_di_mais olio_di_arachidi"],
  ['Strutto', 'Lard', 'grassi', 10, 'strutto sugna'],
  ['Maionese', 'Salad dressing, mayonnaise, regular', 'grassi', 15, 'maionese'],
  ['Pesto alla genovese', 'Sauce, pesto, ready-to-serve, refrigerated', 'grassi', 30, 'pesto'],
  ['Ketchup', 'Catsup', 'condimenti', 15, 'ketchup'],
  ['Senape', 'Mustard, prepared, yellow', 'condimenti', 5, 'senape'],
  ['Aceto', 'Vinegar, red wine', 'condimenti', 10, 'aceto'],
  ['Aceto balsamico', 'Vinegar, balsamic', 'condimenti', 10, 'balsamico'],
  ['Salsa di soia', 'Soy sauce made from soy and wheat (shoyu)', 'condimenti', 10, "soia salsa_di_soia shoyu tamari"],
  ['Brodo vegetale', 'Soup, vegetable broth, ready to serve', 'condimenti', 250, 'brodo dado'],
  ['Brodo di carne', 'Soup, stock, beef, home-prepared', 'condimenti', 250, 'brodo carne'],
  ['Vino bianco', 'Alcoholic beverage, wine, table, white', 'bevande', 100, 'vino bianco'],
  ['Vino rosso', 'Alcoholic beverage, wine, table, red', 'bevande', 150, 'vino rosso'],
  ['Birra', 'Alcoholic beverage, beer, regular, all', 'bevande', 330, 'birra'],

  // Dolci e zuccheri
  ['Zucchero', 'Sugars, granulated', 'dolci', 5, 'zucchero semolato canna velo'],
  ['Miele', 'Honey', 'dolci', 10, 'miele'],
  ['Marmellata', 'Jams and preserves', 'dolci', 20, 'marmellata confettura'],
  ['Cioccolato fondente', 'Chocolate, dark, 70-85% cacao solids', 'dolci', 20, 'cioccolato fondente'],
  ['Cioccolato al latte', 'Candies, milk chocolate', 'dolci', 20, ''],
  ['Cacao amaro', 'Cocoa, dry powder, unsweetened', 'dolci', 5, 'cacao'],
  ['Crema spalmabile nocciole', 'Chocolate-flavored hazelnut spread', 'dolci', 15, 'nutella'],
  ['Biscotti secchi', 'Cookies, butter, commercially prepared, enriched', 'dolci', 10, "biscotti frollini savoiardi amaretti pavesini pasta_frolla"],
  ['Gelato', 'Ice creams, vanilla', 'dolci', 100, 'gelato'],
  ['Amido di mais / fecola', 'Cornstarch', 'dolci', 10, "amido maizena fecola fecola_di_patate"],
  ['Liquore / distillato', 'Alcoholic beverage, distilled, all (gin, rum, vodka, whiskey) 86 proof', 'bevande', 30, 'grappa brandy limoncello liquore rum cognac marsala'],
  ['Besciamella', 'White sauce or gravy', 'uova-latticini', 100, 'besciamella'],
  ['Formaggio fuso a fette', 'Cheese, pasteurized process, American, fortified with vitamin D', 'uova-latticini', 20, 'sottilette'],
  ['Lievito per dolci', { kcal: 53, p: 0, c: 28, f: 0 }, 'dolci', 0, 'lievito'],

  // Bevande e integratori
  ['Caffè', 'Beverages, coffee, brewed, espresso, restaurant-prepared', 'bevande', 30, 'caffè espresso'],
  ['Succo di frutta', 'Orange juice, raw', 'bevande', 200, 'succo'],
  ['Bevanda di mandorla', 'Beverages, almond milk, unsweetened, shelf stable', 'bevande', 200, 'latte di mandorla'],
  ['Proteine whey', 'Beverages, Whey protein powder isolate', 'integratori', 30, "whey proteine_in_polvere"],
];
